### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by antoinewdg** [lumol-org/lumol#104]
[Here](http://lumol-org.github.io/lumol/latest/book/input/systems.html#Specifying%20interactions), at the end of the first paragraph. 
Opening this so that I don't forget to fix it.

**Comment by Luthaf** [comment]
The generation of anchors is now done at compile-time by [mdbook](https://github.com/azerupi/mdBook/pull/207), so we could have another script to run on CI checking that all links are defined in the doc.
