### ISSUE TITLE
Add a CI script to check the links in documentation

### ISSUE THREAD

**Issue by Luthaf** [lumol-org/lumol#106]
All the data (links and targets) should be available after the html is generated for both user manual and API documentation. 

This would need to parse the html and check the validity of all the local links. The rust book and api doc is already doing something like this, we could use the same tools as they do.

We could also check the links on the markdown files/documentation comments before generating HTML.

**Comment by antoinewdg** [comment]
I don't really understand why this is not done by `mdbooks` during the build process, is there a reason for that ?

**Comment by Luthaf** [comment]
I believe it is just not implemented yet: they mention it on the [documentation](https://azerupi.github.io/mdBook/cli/test.html). You are right we should use the functionality from mdbook, either contributing it or waiting for someone to add it.
