### ISSUE TITLE
Tests on lumol core failing on my machine

### ISSUE THREAD

**Issue by antoinewdg** [lumol-org/lumol#107]
All is in the title. As of commit cd2e2c0b I have the followign failure on the core tests:

``` bash
failures:

---- sys::cache::tests::move_atoms stdout ----
        thread 'sys::cache::tests::move_atoms' panicked at 'assertion failed: `(left ≈ right)` (left: `14808.992701116425`, right: `14808.992701116422`) with ∆=3.6e-12 (allowed ∆=1e-14)', src/sys/cache.rs:458

```

It stops failing if we replace it by the `assert_ulps_eq!` macro from [approx](http://brendanzab.github.io/approx/approx/index.html).

**Comment by Luthaf** [comment]
Can you check #108 fixed this? It did on my machine, but better be sure than sorry !

**Comment by antoinewdg** [comment]
It does :+1: .
But this is a reminder that choosing the epsilon values on the float tests is not easy !
