### ISSUE TITLE
Bug in energy caching of Ewald summation

### ISSUE THREAD

**Issue by g-bauer** [lumol-org/lumol#109]
When a particle is moved in a MC move, we compute the energy difference between the trial and the old state, dU. I compared dU computed from scratch (calling `system.total_energy()` before and after a successful move) and the `cost` function, which uses energy caching. There is a difference between both values which leads to an energy drift in the system.

My *guess* is, that it is in the caching of the Ewald summation, since systems without charges are working (did not test Wolf). I will have a look at the different contributions and the caching tests in Ewald.

**Comment by Luthaf** [comment]
There is a [test for that](https://github.com/lumol-org/lumol/blob/cd2e2c0ba943033888cf08492f340db05b5989fa/src/core/src/energy/global/ewald.rs#L1027), but I guess it is not good enough. Can you add your own test case to this test along with the bug fix?

**Comment by Luthaf** [comment]
Also, could you share your failing test code, so that we keep a trace of it and we can reproduce it later?

**Comment by g-bauer** [comment]
The "error" does not occur at every successful move. It might be a case like we had in the normal caching where something went wrong when the change lead to crossing of the cut-off.

> Also, could you share your failing test code, so that we keep a trace of it and we can reproduce it later?

It's the existing spce example where I removed the volume move. I recognized an energy drift and put some print statements in the `propagate` function along with the calls to `system.total_energy()`. I always debug with `println!` 😄 . I could copy the changes I made to `propagate` to this issue if that helps or create a gist?

My debug output looks like this:
```
Accepted! Delta is: 0.00000000000000061138160506457595

Energy before cache: -0.4064535934890183
Energy after cache: -0.40680592448358466
Delta recompute   : -0.00035233099456633
Delta cache       : -0.00009584218212279916
Dif               : 0.00025648881244353083
Accepted! Delta is: 0.0000000000000003900146264973481
.
multiple accepted moves ...
.
Accepted! Delta is: 0.00000000000000072142812557185465

Energy before cache: -0.40629816327772295
Energy after cache: -0.4095718687695045
Delta recompute   : -0.0032737054917815755
Delta cache       : -0.0011707577499085106
Dif               : 0.0021029477418730647
Accepted! Delta is: 0.00000000000000029995130728169284
```

If you have suggestions/tips how to debug more efficiently, I'd love to hear them.

**Comment by Luthaf** [comment]
> It's the existing spce example where I removed the volume move. 

OK, great! I though you had another test here.

> If you have suggestions/tips how to debug more efficiently, I'd love to hear them.

We can add some code to the `MonteCarlo::propagate` function to check the cache every n steps, with n=10000 by default, and set n to a lower value when debugging. I believed we had this in lumol, but it was only in my other code =/.

**Comment by g-bauer** [comment]
It seems I ran an old version of the code that yielded this bug. I can no longer reproduce it in the current version of the code - which is nice. No longer a drift in energy is observed! However, there are problems with the pressure - I will open another issue about that.

I'm sorry if you spent time on this. However, I will implement a check for the cache in the propagation step for debug purposes.
