### ISSUE TITLE
Broken inline math in the manual

### ISSUE THREAD

**Issue by antoinewdg** [lumol-org/lumol#117]
Right now all the inline math in the manual does not work, which is not surprising since it does not use the syntax [indicated in the mdBook docs](http://azerupi.github.io/mdBook/format/mathjax.html). Did it work before, has there been breaking changes in mdBook ?

**Comment by Luthaf** [comment]
This is https://github.com/azerupi/mdBook/issues/227. We configure mathjax to use `$` [here](https://github.com/lumol-org/lumol/blob/528f2d71343c2b3a1c269e543acbc785b4fce233/doc/src/theme/index.hbs#L22-L25), but out custom theme is not picked up by mdbook.

**Comment by antoinewdg** [comment]
So do we actually move the `theme` back into the root `doc` folder ?

**Comment by Luthaf** [comment]
Let's wait a few days to see how this is resolved on the mdbook side, and then fix on our side!
