### ISSUE TITLE
Improving the choice of parameters for Ewald summation method

### ISSUE THREAD

**Issue by antoinewdg** [lumol-org/lumol#119]
Right now the real space cutoff and the k-space cutoff are chosen independently. According to [[Frenkel2002]](http://physicstoday.scitation.org/doi/10.1063/1.881812) section 12.1.5 there is a relation between these values that enables comparable errors for both computations. This means that currently setting the two cutoffs independently makes us do useless computations. 

Is there a reason why we don't use this ?

Then there is the choice of alpha, that is supposed to give us an optimal computation time. This value is potentially machine dependent, so I think we're better off not worrying too much about it right now.

**Comment by Luthaf** [comment]
> Is there a reason why we don't use this ?

Mainly not enough time to do everything! This could be a nice addition. In some packages, the user can simply give the precision wanted, and then both cutoff are computed accordingly. This might be system dependant, so maybe we could have some function like this:

```rust
let mut ewald = Ewald::default();
let mut system =  ...;
ewald.set_precision(1e-6, &system);
system.interactions_mut().set_coulombic(Box::new(ewald));
```

>  This means that currently setting the two cutoffs independently makes us do useless computations.

What make you think it is useless? From my point of view, it is not optimal, but still useful.

**Comment by g-bauer** [comment]
I think the short ranged cut off should always be set by the user (that's what you'll find in most codes). However we could set alpha using either the cutoff or use a precision.

**Comment by antoinewdg** [comment]
> What make you think it is useless? From my point of view, it is not optimal, but still useful.

You're right.

> I think the short ranged cut off should always be set by the user (that's what you'll find in most codes).

You think we could make the user set the short range cutoff, and compute the optimal value for `kmax` from there ?

**Comment by g-bauer** [comment]
> So you think we should make the user set the short range cutoff, and compute the optimal value for kmax from there ?

Yes, and that is mainly motivated by the fact that you will always find information about the real-space cut-offs in publications (and sometimes a tolerance) because it is a quantity that will be used for different methods (PME, Wolf) too. Also, I am used to specify those in the codes I regularly use 😄 . Do you think it would be more transparent to do it differently?
