### ISSUE TITLE
Computing pressure for potentials with explicit volume dependence.

### ISSUE THREAD

**Issue by g-bauer** [lumol-org/lumol#120]
I was looking at simulations of SPC/E water for which I found the pressure to behave strangely (non electrostatic interactions work fine). Digging a bit deeper into Ewald summation (mainly using Tuckerman's book) I stumbled over a different formulation of the pressure (estimator) for potentials that explicitly depend on volume (Eqn 4.6.58):

![equation](https://latex.codecogs.com/gif.latex?P%28%5Cmathbf%7Br%7D%2C%20%5Cmathbf%7Bp%7D%29%20%3D%20%5Cfrac%7B1%7D%7B3V%7D%20%5Cleft%5B%20%5Csum_%7Bi%3D1%7D%5EN%20%5Cfrac%7B%5Cmathbf%7Bp%7D_i%5E2%7D%7Bm_i%7D%20&plus;%20%5Csum_%7Bi%3D1%7D%5EN%20%5Cmathbf%7Br%7D_i%20%5Ccdot%20%5Cmathbf%7BF%7D_i%20-%203V%20%5Cfrac%7B%5Cpartial%20U%7D%7B%5Cpartial%20V%7D%20%5Cright%20%5D)

As you can see, there is an additional contribution that incorporates the volume dependency.

**Comment by Luthaf** [comment]
I have seen this equation, and the last term is usually zero, this is it was not included. Except it is not zero for the Fourier (k-space) part of Ewald summation! I did not though of that =/

I don't know how big the dU/dV corrective term is, but it is definitively worth implementing.

Should we have a separated function for this term, or just include it in the virial term?

**Comment by g-bauer** [comment]
> Should we have a separated function for this term, or just include it in the virial term?

We only have to change it for the pressure, right? So I'd implement it such that forces can still be computed as it is done currently (i.e. not including it into the virial).

**Comment by Luthaf** [comment]
Currently the virial is computed in a separated function from the forces, to ensure we don't have to compute the PBC more than once for each pair. We can change the virial function without changing the force one.

**Comment by Luthaf** [comment]
This is done for Ewald in `kspace_atomic_virial` & `kspace_molecular_virial`. Other potentials can use the same approach of adding the corresponding values to the virial.
