### ISSUE TITLE
Can not build the current master commit

### ISSUE THREAD

**Issue by antoinewdg** [lumol-org/lumol#145]
It's in the title. 
@Luthaf it's on the same commit that travis sent me an error for.

```
$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to select a version for `time` (required by `chrono`):
all possible versions conflict with previously selected versions of `time`
  version 0.1.35 in use by time v0.1.35
  possible versions to select: 0.1.36
```

```
$ git log --oneline -n 4
0bad2100 [doc] document [log] in the user manual
8c745a6e Add tests for logging configuration in input file
28d840b6 Refactor the lumol-input tests runner
55f9097b Add logging configuration in the input files
```

**Comment by Luthaf** [comment]
Same commit but different error. This looks like a dependencies resolver error.

I only get `time` once in the whole dependencies tree (given by `cargo tree`): lumol-input => log4rs => chrono => time. Did you add a constrain on the time crate somewhere? Else, do removing the `Cargo.lock` file improve the issue?

**Comment by antoinewdg** [comment]
> Did you add a constrain on the time crate somewhere?

No.

> Else, do removing the Cargo.lock file improve the issue?

Yes. Isn't this something we are not supposed to do ?

**Comment by Luthaf** [comment]
It doesn't really matter for a library: the Cargo.lock is not part of the repository, and will change from one computer to another. But cargo should handle changes without any issue, so this looks like a cargo issue =)

Does this fix the problem for you?

**Comment by antoinewdg** [comment]
Yep, thanks !
