### ISSUE TITLE
Forces computations should not allocate a force `Vec` and return it

### ISSUE THREAD

**Issue by antoinewdg** [lumol-org/lumol#172]
They should instead take a mutable slice as a parameter. The `Vec` always already exists, so by doing so we:

- use extra memory
- have to manually sum the `Vec` after the calls like [here](https://github.com/lumol-org/lumol/blob/8b410a0457258751b7deb7fbb07c8a8926283230/src/core/src/sys/compute.rs#L102-L104), which is kind of weird

**Comment by Luthaf** [comment]
👍

**Comment by antoinewdg** [comment]
I'll make the changes then :)
