### ISSUE TITLE
TOML highlighting is broken in the user manual

### ISSUE THREAD

**Issue by Luthaf** [lumol-org/lumol#202]
See this screenshot:

![toml-highlight](https://user-images.githubusercontent.com/6141587/31501262-0a84038e-af6a-11e7-8d24-9aac9d5d94db.png)

I am pretty sure it worked at some point, but I can not get it back working. And [highlight.js](https://highlightjs.org/download/) which is used by mdbook, does not support TOML syntax. So maybe it never worked and I am just confused ...

Anyway, I think we should make it work. One solution would be to add support for TOML to highlight.js. Another solution would be to remove the dependency on mdbook and use something else for the input manual. In this case, [sphinx](http://sphinx-doc.org/) is nice and widely used in scientific community, has a better support for math equations, and supports generating PDF. The main downside is that it uses Restructured Text instead of Markdown,  which is a more complex markup language.

What do you think?

**Comment by g-bauer** [comment]
I am in favor of having a separate input manual - no matter if we stick to mdbook or use sphinx. Sphinx works for me (I'm used to work with it in my python stuff) and it supports a lot of different outputs so that's also a plus.

**Comment by g-bauer** [comment]
If we decide for sphinx, where should we put the source?

```
doc/
    manual/
    input_reference/
```

**Comment by Luthaf** [comment]
Separated directories seems fine. What would you put in the manual exactly ? The current part on how to use lumol and the advanced tutorials ?

**Comment by g-bauer** [comment]
The manual could be used to present the general structure of the code, maybe implementation details and the tutorials. If we come to the conclusion that such a manual is not necessary, we could also present the tutorials in form of README.md files in the tutorial directories here on github.

**Comment by Luthaf** [comment]
> The manual could be used to present the general structure of the code, maybe (implementation) details of algorithms used and the tutorials

👍 

I am slightly bothered by the `_` in `input_reference`, so I would prefer it to be named either `input` or `reference`. 

Apart from that, I am open to anything! The [LAMMPS reference](lammps.sandia.gov/doc/Section_commands.html) is very good, we can take inspiration from it.

For the manual/algorithm section, I love the DL_POLY manual: it explains everything starting from the basic math.

**Comment by g-bauer** [comment]
The link to LAMMPS ref seems to be dead. Do you  mean [this](http://lammps.sandia.gov/doc/Manual.html)? 

> I am slightly bothered by the _ in input_reference, so I would prefer it to be named either input or reference.

Sure, we can easily change it.

> For the manual/algorithm section, I love the DL_POLY manual: it explains everything starting from the basic math.

I am actually not sure if we should use both mdbook and sphinx...

**Comment by Luthaf** [comment]
> The link to LAMMPS ref seems to be dead. Do you mean this?

More specifically the section 3: Command. I've updated the link.

> I am actually not sure if we should use both mdbook and sphinx...

No, we should only have one here. Sorry if I was unclear on this point, but having both will be a pain.

**Comment by Luthaf** [comment]
Fixed by #217 !
