### ISSUE TITLE
Possibly bug in `resize` MC move

### ISSUE THREAD

**Issue by g-bauer** [lumol-org/lumol#203]
There is possibly a bug in the `resize` MC move (in [`prepare`](https://github.com/lumol-org/lumol/blob/master/src/core/src/sim/mc/moves/resize.rs#L83-L95)). I think we introduced it when we separated `configuration` and `system`.

This is mainly a remainder for me to have another look at it and to figure out a good integration test for NPT.

**Comment by Luthaf** [comment]
Yeah, I agree with you here: I tried to add NPT MC tests and could not get the pressure to converge. The code was always increasing the cell size, and the pressure went to 0. 

Do you have an idea of what could be going wrong?

**Comment by g-bauer** [comment]
I am not sure and I have to check my old notebooks for the tests I ran back when we implemented the move. I think tests for LJ and rigid LJ chains worked fine, not sure about electrostatic interactions.

What I found confusing when I glanced over the code was this (the lines I marked in `prepare`):
```rust
let old_com = system.molecule_com(mi);
let frac_com = system.cell.fractional(&old_com);
let delta_com = system.cell.cartesian(&frac_com) - old_com;
```
The `delta_com` should always be zero, if I am not mistaken? `cell` is already mutated to have the new shape at this point, i.e. we already called
```rust
system.cell.scale_mut(Matrix3::one() * scaling_factor);
```
I think we changed `system` to `configuration` and at the same time we changed from creating `new_system` to storing `previous`. Or am I missing something?

**Comment by g-bauer** [comment]
Added some suggestions in #103

**Comment by Luthaf** [comment]
> ```rust
> let old_com = system.molecule_com(mi);
> let frac_com = system.cell.fractional(&old_com);
> let delta_com = system.cell.cartesian(&frac_com) - old_com;
> ```

Yes, this should be something like

```rust
let old_com = system.molecule_com(mi);
let frac_com = old_cell.fractional(&old_com);
let delta_com = system.cell.cartesian(&frac_com) - old_com;
```
