### ISSUE TITLE
Convert the user manual and reference to Sphinx

### ISSUE THREAD

**Issue by Luthaf** [lumol-org/lumol#211]
So @g-bauer started this in #209 with the reference, here is a TODO list for the next steps:

- [x] Convert tfrom mdbook to sphinx
    - [x] Convert the user manual to sphinx (`doc/src/concepts`) + FAQ + Installation + introduction;
    - [x] Convert the tutorials to sphinx (`doc/src/tutorials`);
    - [x] Convert the advanced tutorials to sphinx (`doc/src/advanced`);
- [ ] Build the sphinx manual on travis
    - [x] Setup requirements.txt and a Readme about how to build the doc
    - [x] Build the doc on Travis
    - [x] Deploy the built HTML doc on Github pages
    - [ ] Also deploy the built PDF doc on Github pages?
- [x] Remove the previous doc

**Comment by g-bauer** [comment]
I used [pandoc](http://pandoc.org/) to quickly convert to `rst` format. Some manual changes have to be done but it is a good starting point to carry over the `md` files.
