### ISSUE TITLE
How to modify Lorentz−Berthelot combining rules

### ISSUE THREAD

**Issue by Fariba-Asadi** [lumol-org/lumol#231]
Hi everyone, 
I am using GROMACS to simulate water/methane system. I used Lorentz−Berthelot combining rules: 
σMO = (σM + σO)/2
εMO = χ (εMεO)^0.5
where σ and ε are parameters in the Lennard-Jones potential function, and χ is a factor used to adjust the strength of cross interaction between methane and water.

Does anyone know how to change χ to 1.07?

 I will be grateful for any suggestions. 
Fariba

**Comment by Luthaf** [comment]
Hi @Fariba-Asadi. 

This is an issue tracker for the lumol project, which is not at all related to GROMACS.

Lorentz−Berthelot combining rules are not yet implemented in Lumol, they are related to the #7 issue.

I think that the [gromacs users mailling list](http://www.gromacs.org/Support/Mailing_Lists/GMX-Users_List) is a better place to ask such questions.

**Comment by Luthaf** [comment]
(maybe I misunderstood your question. Are you asking about how to modify these parameters while using lumol to run your simulation?)

**Comment by Fariba-Asadi** [comment]
Thank you for your suggestion. I will ask my question from Gromacs users.
