### ISSUE TITLE
Find a better name for the project

### ISSUE THREAD

**Issue by Luthaf** [lumol-org/lumol#24]
`cymbalum` was a temporary initial name for this project. I need ideas for a better name, which must be

- not too long, to be usable as name for a command line tool;
- easy to search in google, thus not too common;
- fun !

**Comment by g-bauer** [comment]
Do you want something that "just sounds good" or should it be an abbreviation? Something related to rust (some rust projects use industrial terms)? Something that catches the essence of molecular simulations?

**Comment by Luthaf** [comment]
I do not think it should be an abbreviation, there are already a lot of projects with abbreviations names.
It does not needs to be rust related either, as "written in rust" is not the main selling point of the code.
Something related to molecular simulation would be nice, but lot of names are already taken.

Also, [this](http://ivantomic.com/projects/ospnc/) is a good tool to check for the availability of a name.

**Comment by Luthaf** [comment]
Some ideas: unipart, particulas, simpart, cusim (customisable simulation), flexim

**Comment by Luthaf** [comment]
More ideas: molbench, simbench (already taken).

In a less descriptive way: some mythological gods of crafting/smithing: Brokk, Tvashtar (both have hard to remember spelling).

**Comment by g-bauer** [comment]
I am not very creative with names...

- customizable simulation package (cusimpa)
- open simulation engine (ose, openSIME, there are similar things out there)
- craft your simulation (crysim)
- Metis (greek, "craft", "skill", "wisdom" - I am sure we could use this as abbreviation, something like "molecular engine to implement simulations")

**Comment by Luthaf** [comment]
> craft your simulation (crysim)

I like this one, it appeals the gamer inside me =)

**Comment by g-bauer** [comment]
Hehe :) Instead of "craft" we could also use "create".

**Comment by Luthaf** [comment]
Yep. I also like OSE a lot, it is french for dare, is a simpler/smaller name, and not used that much on GIthub.

**Comment by Luthaf** [comment]
Yet another idea: omosie/osmosie (Open (Source) Molecular Simulation Engine).

**Comment by g-bauer** [comment]
My favorites are crysim and osmosie (i fear that the latter will result in "osmosis" google hits)

**Comment by Luthaf** [comment]
I like both, but I am not convinced yet. osmosie is too close to osmosis; and crysim is a bit harsh to say.

More propositions, not acronyms this time:
  - atmol (french for workbench is 'atelier')
  - scrow (old word for scroll, close to screw)
  - cymos (variation on crysim)
  - sciums

Some of the previous propositions worth a second tough:
  - flexim
  - crysim
  - ose

**Comment by Luthaf** [comment]
I had another idea after looking for latin words (from *lux/lumina*): `lumol` or `luxmol`.

Both are available on Github and not used in Google. I think they are easy to pronounce in multiple languages, can you confirm for german? Do you have any preference?

**Comment by g-bauer** [comment]
I like `lumol` and yes, it is easy to pronounce even for germans :)

**Comment by Luthaf** [comment]
OK, let's give us a few day, come back and decide if we should pick this one.

**Comment by Luthaf** [comment]
So I went ahead and started the renaming of the code to Lumol. I also created an organisation to have all the repositories at one place, named lumol-org for now.

--

@lumol we are renaming this piece of code to `Lumol`. It is a library for scientific simulations in theoretical chemistry. Since you do not have public activity associated with your Github account, do you think it would be possible for you to change your account name so that we could use `lumol` as organisation name? If not, that is totally fine 👍 If you want more information, please ask!
