### ISSUE TITLE
Is Lumol abandoned?

### ISSUE THREAD

**Issue by lachlansneff** [lumol-org/lumol#264]
I'm working on some software that needs to do complex molecular dynamics simulations in the background. I'd prefer to use a sim written in rust, like Lumol, otherwise I'll probably write a rust  wrapper for openmm. Is this project still in development?

**Comment by Luthaf** [comment]
Hi! Nice to see that they are other people interested in molecular simulation with Rust. Out of personal interest, can you share which generic kind of software you are working on?

I had very little time in the recent months to work on Lumol, as I was writing my thesis. I am however still interested in developing it further, so I do not consider it abandoned!

I am currently starting a postdoc, so I can't make any promise on developing new features, but if there is something specific you need let me know and I'll see what I can do.

----

At the same time, if you need advance simulation features and performances, maybe going with openmm is a better choice: it is much more battle tested and optimized than lumol.

**Comment by lachlansneff** [comment]
Thanks for replying so quickly!

I can't share too much about it, but it consists of modeling molecules and then simulating them along with external forces (e.g. rotational torque on certain particles in a molecule, linear force, forcing certain particles to stay in a specific location, etc). I understand lumol doesn't support these use-cases yet, but this is a _very_ long-term project and I'd be happy to donate development time to lumol to get it further along.

I'd also be interested in working on gpgpu integration for lumol if that's part of your roadmap.

I strongly believe a molecular dynamics simulator written in rust is something that needs to happen.

**Comment by Luthaf** [comment]
> I'd be happy to donate development time to lumol to get it further along.

That's great! I guess you have a background in molecular simulation? 

> I'd also be interested in working on gpgpu integration for lumol if that's part of your roadmap.

This is something I am very interested about, but (1) I have never worked with GPGPU code, and (2) from my understanding the state of Rust ecosystem for GPGPU is still weak.

---

Also, I've seen you worked on WASM, this is another area in which I am interested: using WASM as a way to distribute plugins for lumol. New potentials, integrators, etc. can be written in Rust (and/or C and/or C++), compiled to wasm and distributed as wasm modules.

**Comment by lachlansneff** [comment]
> I guess you have a background in molecular simulation?

I don't. My background is osdev and runtimes, but I've recently gotten very interested in molecular simulation and I'm a quick learner.

> I have never worked with GPGPU code

I haven't done much substantial work with gpgpu either. I'd say that state of rust's gpgpu ecosystem is immature, not weak. [wgpu-rs](https://github.com/gfx-rs/wgpu-rs) is intended to be the core crate for doing compute on gpus with rust, and it's usable.

> WASM

Definitely an interesting idea. Integrating a wasm runtime for lumol plugins would be cool!

**Comment by Luthaf** [comment]
> wgpu-rs is intended to be the core crate for doing compute on gpus with rust, and it's usable.

Ok, didn't knew that! I'll give it a look when I can =)

**Comment by Luthaf** [comment]
I'll close this issue, if you want to continue the discussion, we can use [gitter](https://gitter.im/lumol-org/lumol) or email!
