### ISSUE TITLE
Add computation for truncated potentials with tail corrections  

### ISSUE THREAD

**Issue by g-bauer** [lumol-org/lumol#28]
We should add a struct and computation for truncated intermolecular pair potentials with long range corrections.

In Monte-Carlo (MC) simulations we often use potential functions that are truncated at a cutoff distance `rc`. Since we don't have to evaluate forces in MC, we don't have to shift the potential at the cutoff distance. 

Under the **assumption** that the **pair correlation function is unity beyond `rc`**, we can compute a **tail correction** (for the energy and the pressure) by integration of the pair-potential from `rc` to infinity. For some potentials this can be solved analytically. The tail correction is a function of the cutoff distance `rc` and the ~~systems' density~~ densities of all components (`ParticleKind`).

**Comment by Luthaf** [comment]
I believe this would be better as two additional functions for `PairPotential` trait: 

```rust
trait PairPotential {
   // Default return values is equivalent to today's code
   fn tail_energy(&self, cutoff: f64, density: f64) -> f64 {0.0}
   fn tail_virial(&self, cutoff: f64, density: f64) -> Matrix3 {Matrix3::zero()}
}
```

These function would be called from `System::{energy,virial}` with the actual density of the system, and the half of the lower cell parameter as default cutoff. (Is this correct for non-cubic boxes?)

Then, the `CutoffComputation` can implement these by overwriting the cutoff value.
```rust
impl<T: PairPotential> PairPotential for CutoffComputation<T> {
   fn tail_energy(&self, cutoff: f64, density: f64) -> f64 {
        assert!(cutoff >= self.cutoff, "Cutoff is too big in CutoffComputation");
        self.potential.tail_energy(self.cutoff, density)
   }

   fn tail_virial(&self, cutoff: f64, density: f64) -> Matrix3 {
        assert!(cutoff >= self.cutoff, "Cutoff is too big in CutoffComputation");
        self.potential.tail_virial(self.cutoff, density)
   }
}
```

**Comment by g-bauer** [comment]
That's also possible. Note that potentials that are computed via `CutoffComputation` must not be shifted when cutoff corrections are applied.

**Comment by Luthaf** [comment]
Forgot about this one. Maybe there should be another `Computation`? Like having `CutoffComputation` which only uses a cutoff for MC (but is not shifted), and `ShiftedComputation` which uses a cutoff and shift the potential for MD.

**Comment by g-bauer** [comment]
I'd like to tackle this. The current implementations do not distinguish between inter- and intramolecular potentials. Tail-corrections and shifts are usually only applied to intermolecular potentials. 

Also, there are two correction terms: one for the systems' energy, one for the pressure (not for the forces).

I am not sure where to add this into the code. This is an MC-only issue. A naive implementation looks like this:

```rust
// We only need to recompute the tail-correction when the density or the cut-off changes, e.g. when
// i.e. the box size or shape changes or a molecule is added or deleted from the cell.
// 'self' is an EnergyEvaluator that owns a ref to system
let mut energy = 0.0;                                                   
  for i in 0..self.system.size() {                                                                                                                  
    for j in (i+1)..self.system.size() {                                
      let r = self.system.nearest_image(i, j).norm();                 
      energy += self.pair(r, i, j) + self.tail(i, j, system.density()); // self has to know rc                                   
    }                                                                   
  }                                                                       
return energy 
```

**Comment by Luthaf** [comment]
> This would be the cleanest way I can think of but with a lot of overhead since for every atom pair there is one value for the tail correction.

This is what I had in my head with the `tail_energy` and `tail_virial` functions [here](https://github.com/Luthaf/cymbalum/issues/28#issuecomment-228787280). 

Moving the computation out of the loop can be nice too, but may be harder to get right, as simple scheme like using mole fractions for computation will break for complex systems: how do you apply them for interfaces for example?

> I am not sure where to add this into the code. This is an MC-only issue.

For now, the system have no idea whether it is propagated trough Molecular Dynamics or Monte-Carlo, so the code would need to run every time. I am not too worried about the overhead here, as this is only an `O(1)` cost that is added to the normal computation of pairs energy. 

My idea to get away with the problem "should we compute tail correction" would be to add a specific `CutoffComputation` computation, or a `TailCorrectedLJ` potential, which would be the only one implementing tail corrections.

> The current implementations do not distinguish between inter- and intramolecular potentials. Tail-corrections and shifts are usually only applied to intermolecular potentials.

It does! This is the reason to live for [`PairRestriction`](https://github.com/Luthaf/cymbalum/blob/5edccfebaecbe12823907d6a5d594991f308fe0a/src/potentials/restrictions.rs#L17), which is currently used in the [`Interactions`](https://github.com/Luthaf/cymbalum/blob/5edccfebaecbe12823907d6a5d594991f308fe0a/src/system/interactions.rs#L70). I think they should live inside the `PairPotential` instead, and this would be a nice use case for https://github.com/rust-lang/rfcs/pull/1546. It can still be done "by hand" while waiting, I may do that tonight!

**Comment by g-bauer** [comment]
> Moving the computation out of the loop can be nice too, but may be harder to get right, as simple scheme like using mole fractions for computation will break for complex systems: how do you apply them for interfaces for example?

Corrections only should be applied to bulk systems since the correction assumes pair correlation functions of unity outside the cut off. For interface simulations I'd use a truncated potential.

> My idea to get away with the problem "should we compute tail correction" would be to add a specific CutoffComputation computation, or a TailCorrectedLJ potential, which would be the only one implementing tail corrections.

Ok, I will have a look at this.

**Comment by Luthaf** [comment]
> Corrections only should be applied to bulk systems since the correction assumes pair correlation functions of unity outside the cut off. For interface simulations I'd use a truncated potential.

Ok, so the issue is more about how do you define that you need tail corrections or not.

**Comment by Luthaf** [comment]
Another simpler solution just popped into my mind: why not unify the pair interactions? Having somehting like this:

```rust
pub struct PairInteraction<T: PairPotential> {
    // Use a generic here to remove the function dispatch cost
    potential: T,
    restriction: PairRestriction,
    cutoff: f64,
    shift: Option<f64>,
}

impl<T: PairPotential> PairInteraction<T> {
    fn new(potential: T, cutoff: f64) -> PairInteraction<T> {
        PairInteraction {
            potential: potential,
            restriction: PairRestriction::None,
            cutoff: cutoff,
            shift: None,
        }
    }

    fn shifted(potential: T, cutoff: f64) -> PairInteraction<T> {
        let shift = potential.energy(cutoff);
        PairInteraction {
            potential: potential,
            restriction: PairRestriction::None,
            cutoff: cutoff,
            shift: Some(shift),
        }
    }
}

// Only manipulate PairInteraction as Box<PairPotential> everywhere else in the code, to have a nicer interface.
impl PairPotential for PairInteraction {
   ...
}
```

Allow to have all the information together: the cutoff to use, whether to potential should be shifted or not, and which restriction to use. This would replace the `CutoffComputation`, and remove the need for `ShiftedComputation`.

Then, adding new methods for tail correction to `PairPotential` should be very easy. What do you think?

**Comment by g-bauer** [comment]
I like it. We just have to agree on what we actually want to have: truncation, truncation + shift (which shift?), truncation + tail correction? Should adding a tail correction also be an option? And where to put the pressure correction.

I usually work with:
- truncated (no shift, no correction, for example when simulating interfaces)
- truncated + tail corrected (bulk phases, solids)
- truncated + shifted (without corrections, to compare MD <-> MC data)

**Comment by Luthaf** [comment]
Yes, we need another bool value to know whether we need tail correction or not. An `Option<bool>` is a bit redundant here, a bool is enough.

> which shift?

Shifting so that the potential is zero at the cutoff is the only shift kind I know. Are there any other?

**Comment by g-bauer** [comment]
Ups, you're right `bool` is enough.

>Shifting so that the potential is zero at the cutoff is the only shift kind I know. Are there any other?

You can shift the potential to zero and add another contribution so that the forces are smooth and continuous. I never used that though. Maybe we should go with the basics first.

**Comment by g-bauer** [comment]
I am terribly sorry. My naive implementation is flawed: 

```rust
let mut energy = 0.0;                                                   
  for i in 0..self.system.size() {                                                                                                                  
    for j in (i+1)..self.system.size() {                                
      let r = self.system.nearest_image(i, j).norm();        
      // pseudo code   
      // 'system' has to have access to rc and density
      // The following will not work since there is no tail correction for single interactions
      energy += self.pair(r, i, j) + self.system.tail(i, j);                                  
    }                                                                   
  }                                                                       
return energy 
```

We can not move the correction into the interaction loop. There is a contribution for every atom in the system (`N` contributions). For energies, we evaluate `0.5*N*(N-1)` contributions. We should leave the [potential evaluation](https://github.com/Luthaf/cymbalum/blob/ba768aeff1bccb3e991a6f272006b5e42afafb0f/src/potentials/pairs.rs#L69-L79) untouched (shift etc is still simple) and add the tail corrections somewhere else. For energies maybe inside the `EnergyEvaluator` [here](https://github.com/Luthaf/cymbalum/blob/76659abc4aaefbe75e5b4272b28bf0a049db6fb1/src/system/energy.rs#L48)? We have to have access to the number of atoms of every atom type as well as the systems volume. The total tail correction to the energy is:

```latex
2 * \pi / V \sum_i \sum_j N_i N_j int_{rc}^{\infty} u(r_{ij}) r^2 dr  
```
where `i, j` are atom type indices.

Maybe you have a more elegant solution at hand. Again, sorry for my fallacy and the confusion.

**Comment by Luthaf** [comment]
I am working on this. 

It looks like you need tail corrections for shifted energy too: see [this PDF](https://engineering.ucsb.edu/~shell/che210d/Simulations_of_bulk_phases.pdf), page 6; but as we are using a shift such as `V(rc) = 0`, the expression should be the same as the non-shifted case.

**Comment by g-bauer** [comment]
The lecture notes of Scott Shell are golden. 

> I am working on this.

Awesome. I forgot about the correction terms for the shifted cases. I have never used them to be honest. But to compare MC and MD simulations it is valuable to have them.

**Comment by Luthaf** [comment]
Leaving this open for tracking the implementation of this feature in the input files.
