### ISSUE TITLE
Add cut off distance to `resize` MC move to catch too small volumes

### ISSUE THREAD

**Issue by g-bauer** [lumol-org/lumol#59]
If the box gets too small within a NPT simulation, the cut off radius will be larger than half the minimum box length (`rc > L_min/2`). If that is the case, the simulation should stop with an error.

How to get the largest cut off out of `PairInteractions`?

**Comment by Luthaf** [comment]
To get the cutoff for all pair interaction, one would need to iterate over the values in [`Interactions::pairs`](https://github.com/lumol-org/lumol/blob/677d697b91ba41f0ef6c578968cf1ad8d551df21/src/core/src/sys/interactions.rs#L78), and access the cutoff from here.

The fact that there are both a `System::interaction()` and a `System::interactions_mut()` look like a code smell to me, and maybe we want to have the `System::interactions` field public, or/and move the `ParticleKinds` out of Interactions. We need to think a bit about what are the actual invariant of the `System`, `Interactions` and `ParticleKinds` structs here, to make sure nothing can go wrong after that. They are all linked by `ParticleKind`, which the user should never be able to modify directly. 

Contrary to what I said on Gitter, this does not prevent us from implementing a search for the smallest cutoff radius right now. This could be done right now by adding `all_pairs(&self) -> Vec<&[PairInteraction]>` to `Interactions`, and `PairInteraction::cutoff(&self) -> f64` functions. Then we could look for the smallest cutoff in `McMove::setup` function.

**Comment by g-bauer** [comment]
> Then we could look for the smallest cutoff in McMove::setup function.

I had this wrong. We need to check for the *largest* cut off. I thought of asking for the cut off when calling `Resize::new()` but maybe it is better in `Resize::prepare` since we have access to the `system`.

**Comment by Luthaf** [comment]
>  Doing so instead of McMove::setup limits this case to Resize which eventually makes the McMove routines more general and readable.

Sorry, I though there was a `McMove::setup` function, like the [`Integrator` trait](https://github.com/lumol-org/lumol/blob/677d697b91ba41f0ef6c578968cf1ad8d551df21/src/core/src/sim/md/integrators.rs#L10-L12). My issue with `prepare` is that is is called at every step, while `setup` would be called only once by simulation run.

We should add this function to the `McMove` trait, with a default empty implementation, and call it from `MonteCarlo::setup` for all the moves in the simulation. This would still be limited to Resize, and called only once by simulation.

**Comment by g-bauer** [comment]
> My issue with prepare is that is is called at every step

That's true. It is not very elegant but it creates no noise outside of `Resize::prepare` plus it is cheap compared to the energy computation. But I also have no problem with `McMove::setup` to tackle this issue.

**Comment by g-bauer** [comment]
Addressed in #58

**Comment by Luthaf** [comment]
Aren't we still missing the electrostatic cutoff?

**Comment by g-bauer** [comment]
You are right. Reopened.

**Comment by Luthaf** [comment]
Fixed by #140.
