### ISSUE TITLE
Drift in energy caused by energy cache

### ISSUE THREAD

**Issue by g-bauer** [lumol-org/lumol#64]
I observed a drift in energy for long simulations of LJ particles in the NVT ensemble.

When a move is accepted, I compared the energy delta (energy_new - energy_old) from cache via 
`du_cache = cache.move_particles_cost(...)` versus the difference computed via `system.total_energy()`. Looking at the difference, I found that often the difference is negligible (1e-16) but there are cases when the difference is about 1e-7 to 1e-5.

I think the problem is either `move_particles_cost` or the update function of the cache. As far as I can tell, the initialization of the cache works correctly (tail correction is missing at the moment).

You can find the results from a sample simulation [here](https://github.com/g-bauer/jupyter_notebooks/blob/master/cache_energy_drift.ipynb).

**Comment by Luthaf** [comment]
Fixed by #72
