### ISSUE TITLE
Does the Berendsen Barostat scale intramolecular configurations?

### ISSUE THREAD

**Issue by g-bauer** [lumol-org/lumol#83]
Since I just dove into position scaling for Monte-Carlo volume resizing, I was wondering if one does the same when using the Berendsen Barostat in MD (i.e. only resize the centers of mass, leaving the intramolecular configuration unchanged). Looking at [the integration here](https://github.com/lumol-org/lumol/blob/dbe819f52142470b94bce84472ff768fb8da5374/src/core/src/sim/md/integrators.rs#L199-L200), I found that currently all particle positions are scaled.

**Comment by Luthaf** [comment]
It currently does scale the all the particles positions. I have not seen it described or implemented with center of mass rescaling anywhere, I don't know why. Maybe the algorithm looses some desirable properties when doing that.

---

This make me think that scaling the molecules center of mass is not always the best thing to do even for MC, for example when simulating molecular crystals where the crystal "molecule" would span the entire simulation box. Here trying to do pressure control by rescaling the molecules center of mass would not work, we actually need to rescale the particles positions. This could be an option of the `Resize` move to add after #58 is merged.

**Comment by g-bauer** [comment]
Ok, I skimmed over the original paper (sorry, should have done that beforehand). Both, com-scaling and position scaling works. In the article, they argue that for small molecules with intramolecular constraints, com-scaling is preferable but for large molecules with flexible bonds, particle scaling leads to smoother responses.

> This make me think that scaling the molecules center of mass is not always the best thing to do even for MC, for example when simulating molecular crystals where the crystal "molecule" would span the entire simulation box. Here trying to do pressure control by rescaling the molecules center of mass would not work, we actually need to rescale the particles positions. This could be an option of the Resize move to add after #58 is merged.

It's true, at the moment there would be no way to let the crystal "molecule" adapt to the external pressure using MC. We currently don't implement any moves to change intramolecular structure. It should be easy to modify the rescaling move to allow for intramolecular changes via scaling, but from my experience this leads to very small acceptances or very small amplitudes for volume changes.

For MD it would not be a problem, since intramolecular positions change based on the forces that are computed within the next iteration (before scaling). 

There is another interesting passage in the paper though. They do position updates in different order, after updating the positions:

```rust
part.velocity += 0.5 * dt * self.accelerations[i];
part.position += part.velocity * dt;
// Scale all positions *after* update
part.position *= self.eta;
```

Interestingly, they also say that pressure computation should be done using the forces acting on the molecules' centers of mass (which excludes intramolecular contributions from what I can see). I'll read it more carefully.

Thanks for the comment, I am closing this issue. Maybe we should have a look at the order in which updates are performed to see if it changes anything.

**Comment by Luthaf** [comment]
> Maybe we should have a look at the order in which updates are performed to see if it changes anything.

From what I remember, It had something to do with fitting Berendsen barostat in a Verlet scheme or in a Velocity-Verlet scheme. We are doing the later, the original paper might be doing the former.
