### ISSUE TITLE
Convert integration tests to use input files

### ISSUE THREAD

**Issue by Luthaf** [lumol-org/lumol#96]
Tests in the root `tests` directory are global integration tests. They should use input files to improve readability and consistency.

We will still need some Rust code to check the system properties before/after the run, but hopefully this will be less code.

**Comment by antoinewdg** [comment]
By the way, aren't examples and integration tests a little redundant ?
I don't really like the fact that we don't test our examples right now, so maybe merging integration tests and example would be a win win ?

**Comment by Luthaf** [comment]
I don't think they are completely redundant: examples show how you can do things with the framework, and tests check if the code is right. We will need one example showing how to build a simulation by hand, one using the input system, and some examples showing how to extend the code (new potentials, new integrators, ...)

However, I agree that some examples are redundant and that we should do some cleanup.

> I don't really like the fact that we don't test our examples right now

The code is not run, but it is still compiled by `cargo test`, to prevent bit-rotting.

**Comment by antoinewdg** [comment]
> The code is not run, but it is still compiled by cargo test, to prevent bit-rotting.

Yeah, but half the examples did not work when I tried them even if they compiled. This may not be of critical right now, but when I try out a new lib examples are one of the first things I check out, and if they don't work it's most likely a no-go for me. Maybe just adding a test that runs the example (we would have to set a reasonable number of iterations) would be enough.

I suggest to first get to work on rewriting the tests so that they use input files (I'm starting right now), then we'll see about examples.

**Comment by Luthaf** [comment]
> I suggest to first get to work on rewriting the tests so that they use input files (I'm starting right now)

Nice! Do not hesitate to assign yourself to the issue when you are working on something =)

**Comment by antoinewdg** [comment]
What's the use of dilating the system in [the mc-helium test](https://github.com/lumol-org/lumol/blob/master/tests/mc-helium.rs#L48) ? Is there a way to do this with input files ?

**Comment by Luthaf** [comment]
> What's the use of dilating the system in the mc-helium test ?

The `helium.xyz` file contains a dense helium fluid, which does not behave like a perfect gaz. We dilate it to make it a gaz and test for the perfect gaz equation.

> Is there a way to do this with input files ?

No, and I do not think it is worth it to add. We can use a separated input file with scaled dimensions, or just us a bigger cell and wait for equilibration of the positions (this may need a longer run).

**Comment by antoinewdg** [comment]
@Luthaf thanks, I'll go with a new input file

**Comment by antoinewdg** [comment]
In [this test](https://github.com/antoinewdg/lumol/blob/master/tests/md-nacl.rs#L69) we use a Barostat but no Thermostat, that's the only place I've seen it happen. Is this normal ? Does this have a name (NP something, like we have NVE, NVT and NPT) ?

**Comment by Luthaf** [comment]
> In this test we use a Barostat but no Thermostat, that's the only place I've seen it happen. Is this normal ? Does this have a name (NP something, like we have NVE, NVT and NPT) ?

That is actually an error, the test ought to use a thermostat ... But this ensemble is sometimes called the NPH (H is enthalpy) ensemble, although it is not really used in practise.

**Comment by antoinewdg** [comment]
Well I'll fix this while I'm at it.

**Comment by Luthaf** [comment]
Should we close this? We are still missing the NIST SPC/E tests, but they will not be converted anytime soon.

**Comment by antoinewdg** [comment]
Yes.
